#! /bin/sh

# -----------------------------
# Hardware Acceleration (NVIDIA)
# -----------------------------
export MOZ_X11_EGL=1
export LIBVA_DRIVER_NAME=nvidia
export NVD_BACKEND=direct
export MOZ_DISABLE_RDD_SANDBOX=1
export EGL_PLATFORM=x11

# -----------------------------
# Hotkey daemon
# -----------------------------
pgrep -x sxhkd > /dev/null || sxhkd &

# -----------------------------
# Monitor layout
# -----------------------------

bspc monitor DVI-D-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 10

# -----------------------------
# BSPWM desktops
# -----------------------------
bspc monitor DVI-D-0 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

# -----------------------------
# BSPWM appearance
# -----------------------------
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# -----------------------------
# Window rules
# -----------------------------
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# -----------------------------
# Autostart
# -----------------------------
~/.config/bspwm/autostart &

